language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t uwattotaitai/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true uwattotaitai/docker-react npm run test
